services:
  playlist-api:
    image: ghcr.io/mjsully/playlist-api:latest
    build: ./api/
    container_name: playlist-api
    ports:
      - 8000:8000
    volumes:
      - ./api/data/:/usr/src/app/data/
    env_file: .env
    command: "uvicorn server:app --host 0.0.0.0"
    restart: unless-stopped
  playlist-ui:
    image: ghcr.io/mjsully/playlist-ui
    build: ./ui/
    container_name: playlist-ui
    ports:
      - 3000:3000
    # labels:
    #   - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
volumes:
  playlist-api-data:
